### ISSUE TITLE
Passwords are not encrypted and sent in email as plain text

### ISSUE THREAD

**Issue by dcasbol** [JmlrOrg/webpage#15]
The "sign in" page has no SSL encryption (not https), so the passwords are sent without any encryption.

In the confirmation email, the password is sent to the user as plain text. This is a big security issue, as passwords should not either be sent nor stored as plain text. The recommended form for this is storing a hash of the password+salt and the corresponding salt used.

**Comment by fabianp** [comment]
Thanks for the report @dcasbol . We are aware and working on the problem but solving this requires a massive rewrite of the submission system.

**Comment by fabianp** [comment]
the system should no longer send the password by email upon sign in
