### ISSUE TITLE
misprint in author name

### ISSUE THREAD

**Issue by CRau080** [JmlrOrg/webpage#16]
Dear JMLR Editorial Staff,

I would like to Report a misprint on the page,

http://www.jmlr.org/papers/v18/

One of the author names of the paper,
"Soft Margin Support Vector Classification as Buffered Probability Minimization"
is rendered incorrectly. You may wish to correct this.

Thanking you,
Sincerely,
Christian Rau
Mainz

**Comment by fabianp** [comment]
Thanks a lot for the report @CRau080 . I've pushed a fix for it in fa244c0b45acb557568edb12d5a7297008210533 , should be online in 20 min
