### ISSUE TITLE
Links for cvxpy broken

### ISSUE THREAD

**Issue by SteveDiamond** [JmlrOrg/webpage#21]
The link for my paper, "CVXPY: A Python-Embedded Modeling Language for Convex Optimization" is broken on http://www.jmlr.org/mloss/. The ``code`` link should be changed to https://github.com/cvxgrp/cvxpy and the ``cvxpy.org`` link should be changed to https://www.cvxpy.org/

**Comment by fabianp** [comment]
Thanks for reporting Steve! it should now be fixed. Cheers
