### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by nzhulikov** [JmlrOrg/webpage#23]
I use bookmarks with only icons, so it's impossible now to recognize JMLR website, because it has no favicon.

I made two favicons using your logo on website, feel free to place there one you like the most.

![favicon-1](https://user-images.githubusercontent.com/9846363/77049632-7df13180-69d9-11ea-9ba1-f0e6ec9158b6.jpg)
[jmlr-1.zip](https://github.com/JmlrOrg/webpage/files/4353569/jmlr-1.zip)

![favicon-2](https://user-images.githubusercontent.com/9846363/77049645-82b5e580-69d9-11ea-8d1f-66879a918006.jpg)
[jmlr-2.zip](https://github.com/JmlrOrg/webpage/files/4353568/jmlr-2.zip)

**Comment by fabianp** [comment]
its merged, thanks!
