### ISSUE TITLE
Fix pages field in generated bib files

### ISSUE THREAD

**Issue by fsaad** [JmlrOrg/webpage#35]
The generated bib files on JMLR.org look great. However, there is an issue in that `pages` field uses a single dash `-` instead of a double dash `--`.  The correct symbol for a range of numbers is an en-dash, which in LaTeX is usually input as `--` [(discussion)](https://tex.stackexchange.com/questions/58668/why-should-i-use-in-pages-field-of-a-bibtex-entry).

For example, in this [bib file](https://jmlr.org/papers/v21/16-494.bib)
```
  pages   = {1-24},
```
should instead be generated as
```
  pages   = {1--24},
```

**Comment by fabianp** [comment]
Thanks for the report. I updated the bib template in  d4f7c3c . Might take a few hours to reflect online
