### ISSUE TITLE
Bibtex files contain non-ascii characters

### ISSUE THREAD

**Issue by fsaad** [JmlrOrg/webpage#36]
In the following [bib file](https://jmlr.org/papers/v21/16-494.bib), the non-ascii character `√` is not interpreted correctly by standard pdflatex compilers
```
  title   = {A Low Complexity Algorithm with O(√T) Regret and O(1) Constraint Violations for Online Convex Optimization with Long Term Constraints},
```
![image](https://user-images.githubusercontent.com/5721897/109184036-8eb73500-775c-11eb-8199-fcfdbe1d1212.png)

It requires `\sqrt`.  There may be other examples in the database.

**Comment by fabianp** [comment]
thanks @fsaad for the report. We have this issue with some characters and some accented names. The best practice right now is to use \usepackage[utf8]{inputenc} in the preamble
