### ISSUE TITLE
Add button to email reviewers

### ISSUE THREAD

**Issue by Metaxal** [JmlrOrg/webpage#41]
I like to send an additional personalized email to reviewers (that have actually accepted and submitted a review) after a review round to thank them for their work, but it's cumbersome to figure out their email addresses from the interface.

Is it possible to have a button "Email reviewers", or at least a simple way to obtain the list of emails of the reviewers of the current paper?

Thank you!

**Comment by fabianp** [comment]
CCing @rajarshd @teganmaharaj since they are the persons in charge of the submissions system.

Closing the issue, as this repository is exclusively for the public jmlr.org webpage (not submission system).
