### ISSUE TITLE
multiple author notification emails

### ISSUE THREAD

**Issue by amueller** [JmlrOrg/webpage#42]
I'm not sure if it's just me, but it just happened to me twice that after pressing the "send email" button, the page keeps loading and keeps sending out more and more notifications. I closed the page so it stopped after 14 and 7 respectively...

**Comment by fabianp** [comment]
hey @amueller . Haven't had any other complains about this (yet),  but do let me know if it happens again.

**Comment by amueller** [comment]
seems fixed now. weird. maybe broken cookies?
