### ISSUE TITLE
Times or computer modern?

### ISSUE THREAD

**Issue by wmkoolen** [JmlrOrg/webpage#43]
Dear JMLR,

In the list of of common formatting errors, https://www.jmlr.org/format/formatting-errors.html, it is claimed that text should be in Computer Modern. In the style files it is written it should be in Times Roman.

It appears the list of common formatting errors is out of date.

Cheers,

Wouter

**Comment by fabianp** [comment]
I don't see any reference to Computer Model anymore so I guess this webpage got updated. Please reopen if this is not the case
