### ISSUE TITLE
Conflicting information about parallel submissions

### ISSUE THREAD

**Issue by nikolakon** [JmlrOrg/webpage#46]
Dear JMLR team,

With the current version of the JMLR website, in the "Submissions" section, there is conflicting information about parallel submissions to workshops, conferences, etc. In particular, it is stated that:

"**We will also consider concurrent submissions of papers that are under review at conferences**, provided the conference explicitly allows for this. In this case, too, we expect that the difference between the papers satisfy the above requirements, and we ask authors to provide their conference submission to the JMLR action editor in charge of the JMLR submission."

and, at the same time:

"Articles must be accompanied by a cover letter (in PDF or plain text format) containing all of the below:

Disclosure of any previous publications by the author(s) that significantly overlap with the submission. E.g., if the submission is an extended version of an earlier conference paper, please described the differences between the two papers. **Simultaneous submission of papers to JMLR and other venues is not allowed.**"

Could you please clarify what the exact policy is?

Thank you very much!

**Comment by fabianp** [comment]
thanks for reporting this. The first policy is correct, I'll update the website
