### ISSUE TITLE
Authentication not working - looping forever

### ISSUE THREAD

**Issue by bengio** [JmlrOrg/webpage#49]
When I type my name+pwd to reach my set of assigned papers, the system goes in a loop continuously asking my name+pwd.

**Comment by fabianp** [comment]
@rajarshd @teganmaharaj , could you take a look into this?

**Comment by rajarshd** [comment]
Yes, others are facing this issue too. We have contacted MIT help and will keep this updated.

**Comment by youkaichao** [comment]
I came into this issue several days ago, too. At first I thought my account was stolen and so I reset my password. Then I managed to log in. However, today I faced this issue again :(

**Comment by harmeling** [comment]
Same problem here.

**Comment by teganmaharaj** [comment]
Stefan, have you tried today and still face the same issue?

**Comment by fabianp** [comment]
@youkaichao @harmeling if you have reset your password in the last couple of days, you'll have to either reset it again or use the password you had 2 days ago

**Comment by youkaichao** [comment]
@fabianp thanks. After resetting my password again, I can log in now.
