### ISSUE TITLE
The submission system is currently down, apologies for the inconvenience

### ISSUE THREAD

**Issue by youkaichao** [JmlrOrg/webpage#50]
Hi, I log in to the webpage https://jmlr.org/manudb/ , but it said that "The submission system is currently down, apologies for the inconvenience". What happened?

**Comment by fabianp** [comment]
should be back online, thanks for the report

**Comment by youkaichao** [comment]
@fabianp it seems https://www.jmlr.org/manudb/center/manulist?author is still down with the following error:

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: manudb/center/manulist
RequestId: FMY2H4XJDB4V6HW2
HostId: x29jp/U19XwOYAGE/Tn1BaDLTK9IilIl4dBs9aF+GdNKacjiW1KyhWHV4wnuLjuYKxAVoVvS8Aw=
```

However, I can log in with the url https://jmlr.csail.mit.edu/manudb/center/manulist?author .

**Comment by fabianp** [comment]
replace jmlr.org with jmlr.csail.mit.edu , then it should work

apologies for the inconvenience

**Comment by youkaichao** [comment]
@fabianp Thanks, the jmlr.csail.mit.edu works. Just out of my curiosity, I remember that previously both jmlr.org and jmlr.csail.mit.edu work. Do you mean that jmlr.org would be abandoned? If that is the case, maybe the webpage url at https://www.jmlr.org/author-info.html should be updated (currently it points to http://jmlr.org/manudb ).

**Comment by fabianp** [comment]
thanks for the report @youkaichao , I fixed those URLs (can take up to 1h to reflect in the webpage)

**Comment by fabianp** [comment]
thanks, it fixed now
