### ISSUE TITLE
List of reviewers and action editors no longer load 

### ISSUE THREAD

**Issue by PGijsbers** [JmlrOrg/webpage#51]
On the page https://www.jmlr.org/editorial-board.html there should be lists of people that are AE/reviewer.
Previously it looked like this: https://web.archive.org/web/20220405185716/https://jmlr.org/editorial-board.html
![image](https://user-images.githubusercontent.com/15890747/166979338-e37e524e-e6dc-4820-9ba7-ec0387cafadf.png)
but the live version does not insert the lists:
![image](https://user-images.githubusercontent.com/15890747/166979495-4ef2ce55-d429-4218-b512-c931d3350e44.png)

I tested on Firefox 99.0.1, Chrome 101.0.4951.54 and Edge 101.0.1210.32.

**Comment by fabianp** [comment]
I believe this is fixed now
