### ISSUE TITLE
36 missing papers from Volume 14 on jmlr.org?

### ISSUE THREAD

**Issue by fsaad** [JmlrOrg/webpage#52]
There seem to be several papers missing from JMLR Volume 14: https://www.jmlr.org/papers/v14/.

The papers on the current website start from page 1229, but there are 36 papers from pages 1--1227 that appear to not be listed on the website anymore.  The URLs of the missing papers are in [this text file](https://github.com/JmlrOrg/webpage/files/8710667/jmlr.v14.missing.txt).

The Internet Archive suggests these papers went missing sometime between 02/12/2020 and 04/14/2020 as part of a renaming process that removed the month from the issue number:

  * February 12 2020 [listed papers start from page 1]
  https://web.archive.org/web/20200212014047/https://www.jmlr.org/papers/v14/

  * April 14 2020 [listed papers start from page 1229]
  https://web.archive.org/web/20200414071208/https://www.jmlr.org/papers/v14/

I also noticed that the Internet Archive has the 36 missing papers cached under the "http://jmlr.org" prefix, whereas the remaining papers are under "https://jmlr.org" so that might be partly related to what happened.

**Comment by fabianp** [comment]
Thanks for the report, I'm working on it

**Comment by fabianp** [comment]
After a lot of work I believe this is _finally_ resolved. Please take another look and let me know if something is off.

Thanks again for the report!
