### ISSUE TITLE
Page ranges in generated bib should use en dash `--` not hyphen `-`

### ISSUE THREAD

**Issue by fsaad** [JmlrOrg/webpage#53]
For example in the following bib file: https://jmlr.org/papers/v23/19-267.bib

`pages   = {1-34},` should be `pages   = {1--34},`

The reason is that the correct symbol for a range of numbers in LaTeX is an en-dash, see [here for further discussion](https://tex.stackexchange.com/questions/58668/why-should-i-use-in-pages-field-of-a-bibtex-entry)

**Comment by fabianp** [comment]
thanks @fsaad ! Should be fixed in 2b794969c98739142f57ced85376f20dabd0c28e and reflected online in a few minutes
