### ISSUE TITLE
404 not found on https://www.jmlr.org/reviewer-resources.html

### ISSUE THREAD

**Issue by maksim96** [JmlrOrg/webpage#58]
When I click on "Additional Resources" at the page [https://www.jmlr.org/reviewer-guide.html](https://www.jmlr.org/reviewer-guide.html)  it links to [https://www.jmlr.org/reviewer-resources.html](https://www.jmlr.org/reviewer-resources.html) which gives me a "404 Not Found".

**Comment by fabianp** [comment]
Thanks for the report, it's fixed now
