### ISSUE TITLE
How do I get info.json file from the jmlr.org website.

### ISSUE THREAD

**Issue by bdnettleton** [JmlrOrg/webpage#62]
I'm working with Tegan Maharaj and Koustuv Sinha on setting up the NeurIPS, ICLR and ICML conferences (I see at Tegan has contributed to this repo).  I help maintain and manage the conference websites (eg. https://iclr.cc).

I'm working now on importing titles, abstracts, authors, pdf urls and other information into our conference website.  Poking around some and trying to see if jmlr.org had an API to access this information programmatically, it looks like perhaps there is a file called info.json for each paper, using the paper's jmlr id, which may contain everything I need.

Is there a way to get the info.json file from the jmlr.org website?  I tried a url ending with f"v{volume id}/{paper id}/info.json" but that didn't work.  Is this information available?  Can you send me an example of an info.json file for me to validate my suspicion that the file contains all the data I need?

**Comment by fabianp** [comment]
Hi Brian,

I dont know if we push the json to the jmlr website, but you can find it in
this repo, which you can also access from http. For example
https://github.com/JmlrOrg/v22/blob/main/17-679/info.json

**Comment by bdnettleton** [comment]
Thanks!   

Actually I had found those and thought they were missing one value, namely the 'number' field from the bib file.  However, I just looked again and realized that this is the issue value from the bib file.  These should work fine!  Thanks for your response.
