### ISSUE TITLE
Abstract Has Double Quote Encoding or Escaping Error

### ISSUE THREAD

**Issue by roberts-github-name** [JmlrOrg/webpage#65]
On the latest release of Chrome, the abstract for [this paper](https://jmlr.org/papers/v15/srivastava14a.html) at least (and I assume others too) displays  `â` instead of the double quote character `"`.

I inspected the HTML element with the abstract and saw something like this:
```
<p class="abstract">
" Deep neural nets ... âthinnedâ ... "
</p>
```
The `"` characters are literal double quote characters in the `<p>` element. So the strange glyphs could be the result of an escaping error caused by whatever code takes raw abstract text and escapes it into the `" <your abstract text> "` string in the paragraph element..

**Comment by fabianp** [comment]
Thanks. Should be fixed in https://github.com/JmlrOrg/v15/commit/a42a69055b74452c227cf959e6d9b9a2234f5453 . will be visible next time we generate the webpage
