### ISSUE TITLE
Multiple users with same usernames allowed in the JMLR system

### ISSUE THREAD

**Issue by rajarshd** [JmlrOrg/webpage#66]
Hi,

I am a managing editor and I recently found out that different users with the same username are allowed in the JMLR system. I am not sure if this is a design decision, but I recently encountered an issue in which a reviewer could not access a paper assigned to them. It turned out that the system was recognizing the user as a different user (with the same username) and hence they couldn't access the paper. If it helps, I was able to find this by going to the account page of the user where the details of the other user were being displayed. 

1. Should we allow different users to have same user names?
2. If yes, how can we resolve these edge cases?

Thank you

**Comment by fabianp** [comment]
Hi @rajarshd ,

to whom is this issue directed? This repo exclusively contains the public part of the webpage.
