### ISSUE TITLE
RSS feed change

### ISSUE THREAD

**Issue by alastairrushworth** [JmlrOrg/webpage#67]
Have the RSS feeds changed on jmlr.org?  At the moment, the main feed at [https://jmlr.org/jmlr.xml](https://jmlr.org/jmlr.xml) seems to be empty:

![image](https://github.com/JmlrOrg/webpage/assets/24373730/a22b5e58-3423-4366-b54b-dcecdb933bfb)

**Comment by fabianp** [comment]
thanks for the report. I believe this has been fixed. Please reopen if it hasn't
