### ISSUE TITLE
Official template links are not working

### ISSUE THREAD

**Issue by prithagupta** [JmlrOrg/webpage#68]
- http://www.jmlr.org/format/sample.tex
- http://www.jmlr.org/format/jmlr2e.sty

Please fix the links so that I can check them and make my final submission. 

For now, I am using the following link:
https://github.com/JmlrOrg/jmlr-style-file

**Comment by fabianp** [comment]
hi Pritha,

could you point me to where did you find the below links? the webpage
should only link to the github style sheets

**Comment by prithagupta** [comment]
https://www.jmlr.org/format/format.html
In section:
Formatting Templates

**Comment by fabianp** [comment]
Should be fixed in https://github.com/JmlrOrg/webpage/commit/1e22157a2bd3e0b12901701feb37014550b46b72

might take a few minutes to reflect in the webpage
