### ISSUE TITLE
Registered Users not found

### ISSUE THREAD

**Issue by prithagupta** [JmlrOrg/webpage#71]
Eyke Hüllermeier and Marcel Wever are already registered on your website. However, the system seems unable to recognize or locate their accounts. 

Here are the details of the account:
First Name	Last Name	Username	Email Address
Corresponding	Pritha Gupta	prithagupta	prithag@mail.unipaderborn.de
Author 2	Eyke Hüllermeier	huellermeier	eyke@upb.de
Author 2 (error)	No user matching users found
Author 3	Marcel Wever	wever	marcel.wever@ifi.lmu.de
Author 3 (error)	No user matching users found
Here is the link to the issues:
[Manuscript.Submission.prithagupta.pdf](https://github.com/JmlrOrg/webpage/files/13988150/Manuscript.Submission.prithagupta.pdf)

**Comment by prithagupta** [comment]
The submission worked, but you took two submissions. One with cover letter and one without.

**Comment by Nahian112** [comment]
> The submission worked, but you took two submissions. One with cover letter and one without.

I am facing the same problem while submitting my Manuscript on the JMRL website, How can i solve this?

**Comment by fabianp** [comment]
Eyke Hüllermeier had two accounts, and that sometimes confuses
