### ISSUE TITLE
Missing/Incorrect Link

### ISSUE THREAD

**Issue by prabhatnagarajan** [JmlrOrg/webpage#73]
On the JMLR MLOSS Submission page: https://www.jmlr.org/mloss/mloss-info.html, the text at the bottom 

states 

"When preparing this information, follow the JMLR [instructions](http://jmlr.csail.mit.edu/final_copy.html) for formatting final sumbmissions"

First:
- Typo: sumbmissions -> submissions
- The link to the instructions seems to not work. I think it should link to https://www.jmlr.org/format/authors-guide.html

**Comment by fabianp** [comment]
thanks for reporting this! Should be fixed in https://github.com/JmlrOrg/webpage/commit/35876ad97671ac189695a0967e75aae40a032705

might take a few minutes to reflect online
