### ISSUE TITLE
first author's family name and the title of the paper is misspelled

### ISSUE THREAD

**Issue by Davit1123** [JmlrOrg/webpage#74]
Paper with ID 22-1396

Please correct the spelling of the first author's family name as follows:

misspelled: Arya Akhava

correct spelling: Arya Akhavan (with 'n' in the end)

Correction should also be made to the bib file associated with our paper to ensure citation accuracy.

Also, the title is incorrect:
Current title: "Estimating the Minimizer and the Minimum Value of a Regression Function"

Correct version: "Estimating the Minimizer and the Minimum Value of a Regression Function under Passive Design"

**Comment by kevinsbello** [comment]
Fixed. This error is not due to our system but the authors' incorrect input to the production platform.
